Repository hmcts/adoption-cos-api, pull requests merged in 2023-09, with the labels that each got.

#844 FPET-698-Fixed Nightly fixes
  .github/renovate.json
  audit.json
  build.gradle
Labels: ns:adoption, prd:adoption, rel:adoption-cos-api-pr-844

#846 FPET-698
  audit.json
Labels: ns:adoption, prd:adoption, rel:adoption-cos-api-pr-846

#822 SNI-3911 Added escape character for ' to fix notification service issue
  src/main/java/uk/gov/hmcts/reform/adoption/notification/ApplicationSubmittedNotification.java
Labels: ns:adoption, prd:adoption, rel:adoption-cos-api-pr-822, enable_keep_helm
