Repository hmcts/adoption-cos-api, pull requests merged in 2025-05, with the labels that each got.

#993 bump spring boot
  build.gradle
Labels: ns:adoption, prd:adoption, rel:adoption-cos-api-pr-993

#990 ADOP-2620: Document removal migration
  src/main/java/uk/gov/hmcts/reform/adoption/adoptioncase/event/MigrateCase.java
  src/main/java/uk/gov/hmcts/reform/adoption/adoptioncase/service/MigrateCaseService.java
  src/test/java/uk/gov/hmcts/reform/adoption/adoptioncase/service/MigrateCaseServiceTest.java
Labels: ns:adoption, prd:adoption, rel:adoption-cos-api-pr-990

#992 ADOP- 2669: Fix template
  src/main/resources/application.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-cos-api-pr-992
