Repository hmcts/adoption-cos-api, pull requests merged in 2025-01, with the labels that each got.

#972 ADOP-2555: Retain and Disposal Capability Migration
  src/main/java/uk/gov/hmcts/reform/adoption/adoptioncase/event/MigrateCase.java
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-cos-api-pr-972

#977 [ADOP-2592] + [ADOP-2595] remove demo from automated sync with master
  Jenkinsfile_CNP
Labels: ns:adoption, prd:adoption

#978 Use adoption specific secret for AAT
  build.gradle
Labels: ns:adoption, prd:adoption

#975 [ADOP-2592] + [ADOP-2595] Accessibility Improvements
  src/main/resources/application.yaml
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-cos-api-pr-975
