Repository hmcts/adoption-cos-api, pull requests merged in 2025-06, with the labels that each got.

#982 ADOP-2681 Add CFV tab
  charts/adoption-cos-api/values.preview.template.yaml
  src/main/java/uk/gov/hmcts/reform/adoption/adoptioncase/model/CaseData.java
  src/main/java/uk/gov/hmcts/reform/adoption/adoptioncase/tab/CaseTypeTab.java
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-cos-api-pr-982

#997 ADOP-2670: Swap to Azure Artefacts from JitPack for Dep consuming
  build.gradle
  settings.gradle
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-cos-api-pr-997

#1002 fix dependency vulnerabilities
  build.gradle
Labels: ns:adoption, prd:adoption, rel:adoption-cos-api-pr-1002
